modLoader="javafml"
loaderVersion="[38,)"
license="GNU 3.0"
issueTrackerURL="https://github.com/DancerVlt69/JustMoreSimpleRecipes/issues"

[[mods]]
modId="jmsr_forge"
version = "1.18x-${file.jarVersion}"
displayName="JMSR for Forge"
credits="MCreator was used for the initial version - https://mcreator.net/about"
displayURL="https://www.curseforge.com/minecraft/mc-mods/jmsr-just-more-simple-recipes"
logoFile="logo.png"
authors="DancerVlt69, MCreator"
description='''Just More Simple Recipes (JMSR) will add some useful recipes\nto your Minecraft Java Edition.'''

[[dependencies.jmsr_forge]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.jmsr_forge]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[38,)" #mandatory
    ordering="NONE"
    side="BOTH"
