modLoader="javafml"
loaderVersion="[32,)"
license="GNU 3.0"
issueTrackerURL="https://github.com/DancerVlt69/JustMoreSimpleRecipes/issues"

[[mods]]
modId="jmsr_forge"
version = "${file.jarVersion}"
displayName="JMSR for Forge"
credits="MCreator was used for the initial version - https://mcreator.net/about"
displayURL="https://www.curseforge.com/minecraft/mc-mods/jmsr-just-more-simple-recipes"
logoFile="logo.png"
authors="DancerVlt69, MCreator"
description='''ATM - Simple Recipes (former JMSR) add some useful recipes to your Minecraft Java Edition'''

[[dependencies.jmsr_forge]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.jmsr_forge]]
    modId="forge"
    mandatory=true
    versionRange="[32.,)"
    ordering="NONE"
    side="BOTH"



